version: '3'

services:
  pear-app:
    build:
      dockerfile: ./Dockerfile.dev
    mem_limit: 1024M
    restart: unless-stopped
    networks:
      - default_network
    ports:
      - 3000:3000
      - 10000:10000
    environment:
      PORT: 3000
    command: ["npm", "start"]

networks:
  default_network:
    external: true
